### ISSUE TITLE
Unable to upload file: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by rushkii** [JenSte/aiotus#308]
I was confused where is this error come from, I tried using `traceback` but it doesn't tracing any errors, am I wrong with my code or what? It would be nice if you add more upload methods such as using file bytes, BytesIO, file path string and else.

![image](https://user-images.githubusercontent.com/47179236/203001583-8f5dc0cb-d9d8-4a7e-b754-af935b57741c.png)

**Comment by rushkii** [comment]
> I was confused where is this error come from, I tried using `traceback` but it doesn't tracing any errors, am I wrong with my code or what? It would be nice if you add more upload methods such as using file bytes, BytesIO, file path string and else.
> 
> ![image](https://user-images.githubusercontent.com/47179236/203001583-8f5dc0cb-d9d8-4a7e-b754-af935b57741c.png)

Never mind, my problem is with my `Upload-Metadata` value is not `base64` encoded, you **should** raise an exception instead of just using a **logger**.

**Comment by JenSte** [comment]
> Never mind, my problem is with my `Upload-Metadata` value is not `base64` encoded, you **should** raise an exception instead of just using a **logger**.

The values of the `metadata` dictionary have to be *bytes*-encoded (not *base64*-encoded). It's all documented [here](https://aiotus.readthedocs.io/en/latest/aiotus.html#aiotus.Metadata). And `upload()` does as documented [here](https://aiotus.readthedocs.io/en/latest/aiotus.html#aiotus.upload): Swallows the exception and attempts the underlying operation again, in this case unfortunately swallowing the exception caused by the type violation. As a library author, it's very hard, if not impossible, to protect against such a missuse.
